name: 5min-collector
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      SYMBOLS: ARBUSDT,BTCUSDT,ETHUSDT
      BARS: "60"
      OUTDIR: out
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Collect snapshots
        run: python collector.py
      - name: Commit artifacts
        run: |
          git config user.name "auto"
          git config user.email "auto@users.noreply.github.com"
          git add out/*.csv out/*.json || true
          git commit -m "auto: update panels" || true
          git push
